version: "3"
services:
  xui:
    build: .
    ports:
      - "8090:80"
    volumes:
      - xui_data:/home/xui
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  xui_data:
  mysql_data:
